germany:
  entsoe_code: DE_LU
  latitude: 52.52
  longitude: 13.405
  timezone: Europe/Berlin


greece:
  entsoe_code: GR
  latitude: 37.9838
  longitude: 23.7275
  timezone: Europe/Athens


italy:
  entsoe_code: IT
  latitude: 41.9028
  longitude: 12.4964
  timezone: Europe/Rome


france:
  entsoe_code: FR
  latitude: 48.8566
  longitude: 2.3522
  timezone: Europe/Paris


austria:
  entsoe_code: AT
  latitude: 48.2082
  longitude: 16.3738
  timezone: Europe/Vienna


netherlands:
  entsoe_code: NL
  latitude: 52.3676
  longitude: 4.9041
  timezone: Europe/Amsterdam